# Generated by Django 4.2.13 on 2024-07-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_answer_options_answer_code_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='code_lang',
            field=models.CharField(choices=[('cpp', 'C++')], default=None, max_length=255, null=True, verbose_name='Язык программирования'),
        ),
    ]
