# Generated by Django 3.2.9 on 2024-07-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_answer_text_answer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='code_len',
            field=models.PositiveIntegerField(default=0, verbose_name='Длина ответа'),
        ),
        migrations.AddField(
            model_name='answer',
            name='code_result',
            field=models.TextField(default='', verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Ответ верен'),
        ),
        migrations.AddField(
            model_name='answer',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='task',
            name='example_code',
            field=models.TextField(default='', verbose_name='Код примера'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='code_lang',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JS'), ('cpp', 'C++'), ('c', 'C')], default='', max_length=255, null=True, verbose_name='Язык программирования'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_output',
            field=models.TextField(default='', verbose_name='Ожидаемый вывод'),
        ),
    ]
